language: csharp
solution: BackupUtility.sln
dist: trusty  
install:
 - nuget restore BackupUtility.sln
 - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:  
 - msbuild /t:build /p:Configuration=Release
 ## - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./LiveDirectorySyncEngineTests/bin/Release/LiveDirectorySyncEngineTests.dll
